name: Auto Build TorchVision

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 18 * * *'  # 每天 18:00 UTC 自动执行

jobs:
  get_latest_tag:
    runs-on: macos-15-intel
    outputs:
      version: ${{ steps.get_tag.outputs.version }}
      skip_build: ${{ steps.get_tag.outputs.skip_build }}
    steps:
      - name: Get latest TorchVision stable tag
        id: get_tag
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/pytorch/vision/tags?per_page=100)

          if echo "$RESPONSE" | jq -e 'type=="array"' >/dev/null; then
            LATEST_TAG=$(echo "$RESPONSE" | jq -r '.[].name' | grep '^v[0-9]\+\.[0-9]\+\.[0-9]\+$' | sort -Vr | head -n 1)
          else
            echo "❌ Unexpected response: $RESPONSE"
            exit 1
          fi

          echo "version=${LATEST_TAG#v}" >> $GITHUB_OUTPUT
          echo "Latest tag: $LATEST_TAG"

          # 获取当前 repo 的 Releases
          RELEASES_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases")
          # 判断是否为空数组
          if echo "$RELEASES_JSON" | jq -e 'length == 0' >/dev/null; then
            echo "ℹ️ No releases found. Will proceed to build $LATEST_TAG."
            echo "skip_build=false" >> $GITHUB_OUTPUT
          else
            EXISTING_TAGS=$(echo "$RELEASES_JSON" | jq -r '.[].tag_name')
            if echo "$EXISTING_TAGS" | grep -q "^$LATEST_TAG$"; then
              echo "✅ $LATEST_TAG already in releases. Skipping build."
              echo "skip_build=true" >> $GITHUB_OUTPUT
            else
              echo "⏳ $LATEST_TAG not released. Will proceed to build and upload."
              echo "skip_build=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Stop early if already built
        if: steps.get_tag.outputs.skip_build == 'true'
        run: |
          echo "✅ Build skipped."

      - name: Restore TorchVision source from cache
        if: steps.get_tag.outputs.skip_build == 'false'
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: vision
          key: vision-${{ steps.get_tag.outputs.version }}

      - name: Clone TorchVision repo
        if: steps.get_tag.outputs.skip_build == 'false' && steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch "v${{ steps.get_tag.outputs.version }}" --recursive https://github.com/pytorch/vision.git vision
          git -C vision submodule update --init --recursive --depth 1 || git -C vision submodule update --init --recursive --depth 10 || git -C vision submodule update --init --recursive

      - name: Save TorchVision source to cache
        id: cache-save
        if: steps.get_tag.outputs.skip_build == 'false' && steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: vision
          key: vision-${{ steps.get_tag.outputs.version }}

  build:
    runs-on: macos-13
    needs: get_latest_tag
    if: needs.get_latest_tag.outputs.skip_build == 'false'
    strategy:
      matrix:
        python_version: [ 3.11, 3.12, 3.13 ]
    name: Build TorchVision for Python ${{ matrix.python_version }}
    steps:
      - name: Restore TorchVision source from cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: vision
          key: vision-${{ needs.get_latest_tag.outputs.version }}

      - name: Clone TorchVision repo
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch "v${{ needs.get_latest_tag.outputs.version }}" --recursive https://github.com/pytorch/vision.git vision
          git -C vision submodule update --init --recursive --depth 1 || git -C vision submodule update --init --recursive --depth 10 || git -C vision submodule update --init --recursive

      - name: Build wheel
        run: |
          set -e
          brew install jpeg
          sudo xcode-select --switch /Applications/Xcode_15.2.app

          export BUILD_VERSION=${VERSION}
          export MAX_JOBS=$(sysctl -n hw.logicalcpu)
          if [ "$MAX_JOBS" -gt 4 ]; then
              export MAX_JOBS=4
          fi
          export TORCHVISION_INCLUDE="/usr/local/opt/jpeg/include"
          export TORCHVISION_LIBRARY="/usr/local/opt/jpeg/lib"

          export CMAKE_OSX_ARCHITECTURES="x86_64"
          export _PYTHON_HOST_PLATFORM="macosx-10.13-$CMAKE_OSX_ARCHITECTURES"
          export MACOSX_DEPLOYMENT_TARGET=11.0
          export CC="/Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
          export CXX="/Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export LDSHARED="clang -bundle -undefined dynamic_lookup -isysroot $SDKROOT -arch $CMAKE_OSX_ARCHITECTURES"

          PY_SHORT=$(echo "${{ matrix.python_version }}" | sed 's/\.//')

          wget https://github.com/Morton-Li/PyTorch-MacOS-Builder/releases/download/v${TORCH_VERSION}/torch-${TORCH_VERSION}-cp$PY_SHORT-cp$PY_SHORT-macosx_11_0_$CMAKE_OSX_ARCHITECTURES.whl

          mkdir -p wheels

          python${{ matrix.python_version }} -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install torch-${TORCH_VERSION}-cp$PY_SHORT-cp$PY_SHORT-macosx_11_0_$CMAKE_OSX_ARCHITECTURES.whl
          pip install --force-reinstall cmake==3.25.2 numpy==1.26.4

          cd vision
          git clean -xfd
          
          python setup.py bdist_wheel --plat-name=macosx_11_0_$CMAKE_OSX_ARCHITECTURES

          cp dist/*.whl ../wheels/
          cd ..
          
          if [ "$(ls wheels/*.whl 2>/dev/null | wc -l)" -eq 0 ]; then
            echo "❌ No wheel built. Tag will not be created."
            exit 1
          fi

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vision-${{ needs.get_latest_tag.outputs.version }}-py${{ matrix.python_version }}-macosx-wheel
          path: wheels/*.whl

  release:
    needs: [ get_latest_tag, build ]
    if: needs.get_latest_tag.outputs.skip_build == 'false'
    runs-on: macos-15-intel
    name: Create release and upload wheels
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: wheels
          merge-multiple: true

      - name: Create release and upload wheels
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.get_latest_tag.outputs.version }}
          name: "TorchVision ${{ needs.get_latest_tag.outputs.version }} Release"
          files: wheels/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
